<?
$starttime = microtime(true);

$val = '';
for ($x=0; $x < 1000000; $x++) {
  $str = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies magna et maximus congue. Curabitur sed fringilla dolor. Donec facilisis lectus justo. Curabitur sodales velit ut massa volutpat gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam erat volutpat. Aenean urna nibh, mattis sed sollicitudin non, pharetra ac ligula. Fusce aliquet augue non risus ullamcorper posuere. Quisque egestas egestas massa sit amet ullamcorper. Integer tellus odio, egestas in porta in, tincidunt sit amet turpis. Proin aliquet id urna vitae ullamcorper. Nulla feugiat eget dui sit amet finibus.

Aenean ut nibh sed massa venenatis consequat. Nulla justo lorem, consequat et tristique ut, venenatis sit amet libero. Aliquam pellentesque erat vel justo faucibus, nec laoreet massa sodales. Aliquam ut luctus eros. Etiam sit amet metus vel ipsum rhoncus eleifend. Aenean viverra id mi vel faucibus. Quisque blandit dui lacus, nec pellentesque tortor iaculis sed. Donec elementum iaculis efficitur. In id mauris convallis, tincidunt elit non, auctor ante. Donec congue leo sit amet tellus lobortis pulvinar. Pellentesque ut malesuada est. Vivamus eget augue in dui blandit venenatis auctor vel sapien. Phasellus vel dui gravida, aliquet arcu at, pretium magna. Sed nec nisi dapibus, fringilla mauris ac, dictum tortor.

Aliquam ultrices gravida mattis. Maecenas quis bibendum enim, eget convallis neque. Nulla scelerisque sapien et massa ullamcorper, vestibulum ultrices augue tristique. Sed non ante varius, porttitor erat eu, egestas urna. Integer tempus elementum neque, facilisis vehicula dolor lobortis eget. Pellentesque pharetra lacinia nisi id sagittis. Pellentesque eleifend, nulla nec accumsan eleifend, massa purus rhoncus arcu, non porta sapien ante ac ante. Nulla in felis ut orci finibus vestibulum. Vivamus urna ante, placerat ac auctor ac, tincidunt a nisi. Integer a mi aliquam, pharetra enim in, commodo massa. Vestibulum sed mattis mauris. Pellentesque aliquet mollis sapien, luctus lobortis dui tempus eu. Nam sed urna a ex ultrices congue.

Duis lobortis tempus lectus vel efficitur. Integer bibendum risus ut ipsum commodo, quis facilisis quam dictum. Morbi in ex pharetra velit blandit placerat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce laoreet nunc sed purus consequat, sed ornare metus vestibulum. Aenean pretium elit vel urna molestie, vel vestibulum mauris condimentum. Nullam eu eros commodo, semper lectus sed, rhoncus tellus. Maecenas laoreet in leo eget rutrum. Maecenas ipsum ipsum, venenatis id dapibus non, pulvinar sit amet augue. Praesent a lobortis mi.

Donec porttitor eros diam, sit amet consectetur lacus mattis a. Suspendisse porta nunc augue, sed vehicula lorem congue non. Phasellus ut varius augue. Maecenas molestie risus id lacinia imperdiet. Nulla at odio quis quam euismod cursus vel eu mi. Phasellus et eros felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies magna et maximus congue. Curabitur sed fringilla dolor. Donec facilisis lectus justo. Curabitur sodales velit ut massa volutpat gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam erat volutpat. Aenean urna nibh, mattis sed sollicitudin non, pharetra ac ligula. Fusce aliquet augue non risus ullamcorper posuere. Quisque egestas egestas massa sit amet ullamcorper. Integer tellus odio, egestas in porta in, tincidunt sit amet turpis. Proin aliquet id urna vitae ullamcorper. Nulla feugiat eget dui sit amet finibus.

Aenean ut nibh sed massa venenatis consequat. Nulla justo lorem, consequat et tristique ut, venenatis sit amet libero. Aliquam pellentesque erat vel justo faucibus, nec laoreet massa sodales. Aliquam ut luctus eros. Etiam sit amet metus vel ipsum rhoncus eleifend. Aenean viverra id mi vel faucibus. Quisque blandit dui lacus, nec pellentesque tortor iaculis sed. Donec elementum iaculis efficitur. In id mauris convallis, tincidunt elit non, auctor ante. Donec congue leo sit amet tellus lobortis pulvinar. Pellentesque ut malesuada est. Vivamus eget augue in dui blandit venenatis auctor vel sapien. Phasellus vel dui gravida, aliquet arcu at, pretium magna. Sed nec nisi dapibus, fringilla mauris ac, dictum tortor.

Aliquam ultrices gravida mattis. Maecenas quis bibendum enim, eget convallis neque. Nulla scelerisque sapien et massa ullamcorper, vestibulum ultrices augue tristique. Sed non ante varius, porttitor erat eu, egestas urna. Integer tempus elementum neque, facilisis vehicula dolor lobortis eget. Pellentesque pharetra lacinia nisi id sagittis. Pellentesque eleifend, nulla nec accumsan eleifend, massa purus rhoncus arcu, non porta sapien ante ac ante. Nulla in felis ut orci finibus vestibulum. Vivamus urna ante, placerat ac auctor ac, tincidunt a nisi. Integer a mi aliquam, pharetra enim in, commodo massa. Vestibulum sed mattis mauris. Pellentesque aliquet mollis sapien, luctus lobortis dui tempus eu. Nam sed urna a ex ultrices congue.

Duis lobortis tempus lectus vel efficitur. Integer bibendum risus ut ipsum commodo, quis facilisis quam dictum. Morbi in ex pharetra velit blandit placerat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce laoreet nunc sed purus consequat, sed ornare metus vestibulum. Aenean pretium elit vel urna molestie, vel vestibulum mauris condimentum. Nullam eu eros commodo, semper lectus sed, rhoncus tellus. Maecenas laoreet in leo eget rutrum. Maecenas ipsum ipsum, venenatis id dapibus non, pulvinar sit amet augue. Praesent a lobortis mi.

Donec porttitor eros diam, sit amet consectetur lacus mattis a. Suspendisse porta nunc augue, sed vehicula lorem congue non. Phasellus ut varius augue. Maecenas molestie risus id lacinia imperdiet. Nulla at odio quis quam euismod cursus vel eu mi. Phasellus et eros felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies magna et maximus congue. Curabitur sed fringilla dolor. Donec facilisis lectus justo. Curabitur sodales velit ut massa volutpat gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam erat volutpat. Aenean urna nibh, mattis sed sollicitudin non, pharetra ac ligula. Fusce aliquet augue non risus ullamcorper posuere. Quisque egestas egestas massa sit amet ullamcorper. Integer tellus odio, egestas in porta in, tincidunt sit amet turpis. Proin aliquet id urna vitae ullamcorper. Nulla feugiat eget dui sit amet finibus.

Aenean ut nibh sed massa venenatis consequat. Nulla justo lorem, consequat et tristique ut, venenatis sit amet libero. Aliquam pellentesque erat vel justo faucibus, nec laoreet massa sodales. Aliquam ut luctus eros. Etiam sit amet metus vel ipsum rhoncus eleifend. Aenean viverra id mi vel faucibus. Quisque blandit dui lacus, nec pellentesque tortor iaculis sed. Donec elementum iaculis efficitur. In id mauris convallis, tincidunt elit non, auctor ante. Donec congue leo sit amet tellus lobortis pulvinar. Pellentesque ut malesuada est. Vivamus eget augue in dui blandit venenatis auctor vel sapien. Phasellus vel dui gravida, aliquet arcu at, pretium magna. Sed nec nisi dapibus, fringilla mauris ac, dictum tortor.

Aliquam ultrices gravida mattis. Maecenas quis bibendum enim, eget convallis neque. Nulla scelerisque sapien et massa ullamcorper, vestibulum ultrices augue tristique. Sed non ante varius, porttitor erat eu, egestas urna. Integer tempus elementum neque, facilisis vehicula dolor lobortis eget. Pellentesque pharetra lacinia nisi id sagittis. Pellentesque eleifend, nulla nec accumsan eleifend, massa purus rhoncus arcu, non porta sapien ante ac ante. Nulla in felis ut orci finibus vestibulum. Vivamus urna ante, placerat ac auctor ac, tincidunt a nisi. Integer a mi aliquam, pharetra enim in, commodo massa. Vestibulum sed mattis mauris. Pellentesque aliquet mollis sapien, luctus lobortis dui tempus eu. Nam sed urna a ex ultrices congue.

Duis lobortis tempus lectus vel efficitur. Integer bibendum risus ut ipsum commodo, quis facilisis quam dictum. Morbi in ex pharetra velit blandit placerat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce laoreet nunc sed purus consequat, sed ornare metus vestibulum. Aenean pretium elit vel urna molestie, vel vestibulum mauris condimentum. Nullam eu eros commodo, semper lectus sed, rhoncus tellus. Maecenas laoreet in leo eget rutrum. Maecenas ipsum ipsum, venenatis id dapibus non, pulvinar sit amet augue. Praesent a lobortis mi.

Donec porttitor eros diam, sit amet consectetur lacus mattis a. Suspendisse porta nunc augue, sed vehicula lorem congue non. Phasellus ut varius augue. Maecenas molestie risus id lacinia imperdiet. Nulla at odio quis quam euismod cursus vel eu mi. Phasellus et eros felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies magna et maximus congue. Curabitur sed fringilla dolor. Donec facilisis lectus justo. Curabitur sodales velit ut massa volutpat gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam erat volutpat. Aenean urna nibh, mattis sed sollicitudin non, pharetra ac ligula. Fusce aliquet augue non risus ullamcorper posuere. Quisque egestas egestas massa sit amet ullamcorper. Integer tellus odio, egestas in porta in, tincidunt sit amet turpis. Proin aliquet id urna vitae ullamcorper. Nulla feugiat eget dui sit amet finibus.

Aenean ut nibh sed massa venenatis consequat. Nulla justo lorem, consequat et tristique ut, venenatis sit amet libero. Aliquam pellentesque erat vel justo faucibus, nec laoreet massa sodales. Aliquam ut luctus eros. Etiam sit amet metus vel ipsum rhoncus eleifend. Aenean viverra id mi vel faucibus. Quisque blandit dui lacus, nec pellentesque tortor iaculis sed. Donec elementum iaculis efficitur. In id mauris convallis, tincidunt elit non, auctor ante. Donec congue leo sit amet tellus lobortis pulvinar. Pellentesque ut malesuada est. Vivamus eget augue in dui blandit venenatis auctor vel sapien. Phasellus vel dui gravida, aliquet arcu at, pretium magna. Sed nec nisi dapibus, fringilla mauris ac, dictum tortor.

Aliquam ultrices gravida mattis. Maecenas quis bibendum enim, eget convallis neque. Nulla scelerisque sapien et massa ullamcorper, vestibulum ultrices augue tristique. Sed non ante varius, porttitor erat eu, egestas urna. Integer tempus elementum neque, facilisis vehicula dolor lobortis eget. Pellentesque pharetra lacinia nisi id sagittis. Pellentesque eleifend, nulla nec accumsan eleifend, massa purus rhoncus arcu, non porta sapien ante ac ante. Nulla in felis ut orci finibus vestibulum. Vivamus urna ante, placerat ac auctor ac, tincidunt a nisi. Integer a mi aliquam, pharetra enim in, commodo massa. Vestibulum sed mattis mauris. Pellentesque aliquet mollis sapien, luctus lobortis dui tempus eu. Nam sed urna a ex ultrices congue.

Duis lobortis tempus lectus vel efficitur. Integer bibendum risus ut ipsum commodo, quis facilisis quam dictum. Morbi in ex pharetra velit blandit placerat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce laoreet nunc sed purus consequat, sed ornare metus vestibulum. Aenean pretium elit vel urna molestie, vel vestibulum mauris condimentum. Nullam eu eros commodo, semper lectus sed, rhoncus tellus. Maecenas laoreet in leo eget rutrum. Maecenas ipsum ipsum, venenatis id dapibus non, pulvinar sit amet augue. Praesent a lobortis mi.

Donec porttitor eros diam, sit amet consectetur lacus mattis a. Suspendisse porta nunc augue, sed vehicula lorem congue non. Phasellus ut varius augue. Maecenas molestie risus id lacinia imperdiet. Nulla at odio quis quam euismod cursus vel eu mi. Phasellus et eros felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies magna et maximus congue. Curabitur sed fringilla dolor. Donec facilisis lectus justo. Curabitur sodales velit ut massa volutpat gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam erat volutpat. Aenean urna nibh, mattis sed sollicitudin non, pharetra ac ligula. Fusce aliquet augue non risus ullamcorper posuere. Quisque egestas egestas massa sit amet ullamcorper. Integer tellus odio, egestas in porta in, tincidunt sit amet turpis. Proin aliquet id urna vitae ullamcorper. Nulla feugiat eget dui sit amet finibus.

Aenean ut nibh sed massa venenatis consequat. Nulla justo lorem, consequat et tristique ut, venenatis sit amet libero. Aliquam pellentesque erat vel justo faucibus, nec laoreet massa sodales. Aliquam ut luctus eros. Etiam sit amet metus vel ipsum rhoncus eleifend. Aenean viverra id mi vel faucibus. Quisque blandit dui lacus, nec pellentesque tortor iaculis sed. Donec elementum iaculis efficitur. In id mauris convallis, tincidunt elit non, auctor ante. Donec congue leo sit amet tellus lobortis pulvinar. Pellentesque ut malesuada est. Vivamus eget augue in dui blandit venenatis auctor vel sapien. Phasellus vel dui gravida, aliquet arcu at, pretium magna. Sed nec nisi dapibus, fringilla mauris ac, dictum tortor.

Aliquam ultrices gravida mattis. Maecenas quis bibendum enim, eget convallis neque. Nulla scelerisque sapien et massa ullamcorper, vestibulum ultrices augue tristique. Sed non ante varius, porttitor erat eu, egestas urna. Integer tempus elementum neque, facilisis vehicula dolor lobortis eget. Pellentesque pharetra lacinia nisi id sagittis. Pellentesque eleifend, nulla nec accumsan eleifend, massa purus rhoncus arcu, non porta sapien ante ac ante. Nulla in felis ut orci finibus vestibulum. Vivamus urna ante, placerat ac auctor ac, tincidunt a nisi. Integer a mi aliquam, pharetra enim in, commodo massa. Vestibulum sed mattis mauris. Pellentesque aliquet mollis sapien, luctus lobortis dui tempus eu. Nam sed urna a ex ultrices congue.

Duis lobortis tempus lectus vel efficitur. Integer bibendum risus ut ipsum commodo, quis facilisis quam dictum. Morbi in ex pharetra velit blandit placerat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce laoreet nunc sed purus consequat, sed ornare metus vestibulum. Aenean pretium elit vel urna molestie, vel vestibulum mauris condimentum. Nullam eu eros commodo, semper lectus sed, rhoncus tellus. Maecenas laoreet in leo eget rutrum. Maecenas ipsum ipsum, venenatis id dapibus non, pulvinar sit amet augue. Praesent a lobortis mi.

Donec porttitor eros diam, sit amet consectetur lacus mattis a. Suspendisse porta nunc augue, sed vehicula lorem congue non. Phasellus ut varius augue. Maecenas molestie risus id lacinia imperdiet. Nulla at odio quis quam euismod cursus vel eu mi. Phasellus et eros felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.';

  $val = $str.$x;
}

$interval = (microtime(true) - $starttime) * 1000;
echo print_r('Done', 1)."\n";
echo 'PHP script ('.basename(__FILE__).') took '.$interval.'ms';
